import { Prdlist } from './App';
let data:Prdlist[] = [
  {
    id: 0,
    title: "갸또 쇼콜라",
    price: 38000,
    icon: "",
    edate: "제조일로부터 5일",
    smethod: "냉장보관",
    imgurl: "/img/product1.jpg",
    category: "케이크",
  },
  {
    id: 1,
    title: "쉭쎄",
    price: 29000,
    icon: "",
    edate: "제조일로부터 8일",
    smethod: "냉장보관",
    imgurl: "/img/product2.jpg",
    category: "케이크",
  },
  {
    id: 2,
    title: "초코 구운과자 묶음 (4+1)",
    price: 9200,
    icon: "/img/newicon.gif",
    edate: "별도 표기일까지",
    smethod: "직사광선을 피하고 서늘한 곳 보관",
    imgurl: "/img/product3.jpg",
    category: "초콜렛",
  },
  {
    id: 3,
    title: "통팥앙금빵(6EA)",
    price: 13000,
    icon: "",
    edate: "별도 표기일까지",
    smethod: "직사광선을 피하고 서늘한 곳 보관 (하절기 냉장보관)",
    imgurl: "/img/product4.jpg",
    category: "빵",
  },
  {
    id: 4,
    title: "당근케익",
    price: 5500,
    icon: "/img/newicon.gif",
    edate: "제조일로부터 5일까지",
    smethod: "직사광선을 피하고 서늘한 곳 보관 (개봉 후 냉장보관)",
    imgurl: "/img/product5.jpg",
    category: "케이크",
  },
  {
    id: 5,
    title: "애플파이",
    price: 18000,
    icon: "",
    edate: "제조일로부터 5일까지",
    smethod: "직사광선을 피하고 서늘한 곳 보관 (개봉 후 냉장보관)",
    imgurl: "/img/product6.jpg",
    category: "빵",
  },
  {
    id: 6,
    title: "카스텔라",
    price: 18000,
    icon: "",
    edate: "제조일로부터 10일까지",
    smethod: "직사광선을 피하고 서늘한 곳 보관 (하절기 냉장보관)",
    imgurl: "/img/product7.jpg",
    category: "빵",
  },
  {
    id: 7,
    title: "밤만주 세트",
    price: 17000,
    icon: "",
    edate: "제조일로부터 10일까지",
    smethod: "직사광선을 피하고 서늘한 곳 보관 (하절기 냉장보관)",
    imgurl: "/img/product8.jpg",
    category: "빵",
  },
  {
    id: 8,
    title: "파인치즈 케익",
    price: 37000,
    icon: "/img/newicon.gif",
    edate: "제조일로부터 7일",
    smethod: "냉장보관",
    imgurl: "/img/product9.jpg",
    category: "케이크",
  },
  {
    id: 9,
    title: "다쿠와즈(6EA)",
    price: 14800,
    icon: "/img/newicon.gif",
    edate: "제조일로부터 25일",
    smethod: "직사광선을 피하고 서늘한 곳 보관 (하절기 냉장보관)",
    imgurl: "/img/product10.jpg",
    category: "빵",
  },
  {
    id: 10,
    title: "브라우니(8EA)",
    price: 18600,
    icon: "/img/newicon.gif",
    edate: "제조일로부터 25일",
    smethod: "직사광선을 피하고 서늘한 곳 보관 (하절기 냉장보관)",
    imgurl: "/img/product11.jpg",
    category: "빵",
  },
  {
    id: 11,
    title: "아몬드 쇼꼴라 2종",
    price: 6500,
    icon: "/img/newicon.gif",
    edate: "제조일로부터 2개월까지",
    smethod: "직사광선을 피하고 서늘한 곳 보관 (개봉 후 냉장보관)",
    imgurl: "/img/product12.jpg",
    category: "초콜렛",
  },
  {
    id: 12,
    title: "후랑보아즈",
    price: 35000,
    icon: "/img/newicon.gif",
    edate: "제조일로부터 5일",
    smethod: "냉장보관",
    imgurl: "/img/product13.jpg",
    category: "케이크",
  },
  {
    id: 13,
    title: "스위스롤 & 말차롤케익 [반피스 2종]",
    price: 16000,
    icon: "/img/newicon.gif",
    edate: "제조일로부터 20일",
    smethod: "직사광선을 피하고 서늘한 곳 보관 (하절기 냉장보관)",
    imgurl: "/img/product14.jpg",
    category: "빵",
  },
  {
    id: 14,
    title: "따블렛",
    price: 12000,
    icon: "/img/newicon.gif",
    edate: "제조일로부터 6개월까지",
    smethod: "개봉 후 냉장보관",
    imgurl: "/img/product15.jpg",
    category: "초콜렛",
  },
  {
    id: 15,
    title: "바따르",
    price: 4200,
    icon: "/img/newicon.gif",
    edate: "제조일로부터 5일",
    smethod: "직사광선을 피하고 서늘한 곳 보관(개봉 후 냉장보관)",
    imgurl: "/img/product16.jpg",
    category: "빵",
  },
  {
    id: 16,
    title: "뺑 드 세글",
    price: 8000,
    icon: "/img/newicon.gif",
    edate: "제조일로부터 5일",
    smethod: "직사광선을 피하고 서늘한 곳 보관(개봉 후 냉장보관)",
    imgurl: "/img/product17.jpg",
    category: "빵",
  },
];

export default data;
